// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cyber_conf.proto

#ifndef PROTOBUF_INCLUDED_cyber_5fconf_2eproto
#define PROTOBUF_INCLUDED_cyber_5fconf_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "scheduler_conf.pb.h"
#include "transport_conf.pb.h"
#include "run_mode_conf.pb.h"
#include "perf_conf.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_cyber_5fconf_2eproto 

namespace protobuf_cyber_5fconf_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_cyber_5fconf_2eproto
namespace apollo {
namespace cyber {
namespace proto {
class CyberConfig;
class CyberConfigDefaultTypeInternal;
extern CyberConfigDefaultTypeInternal _CyberConfig_default_instance_;
}  // namespace proto
}  // namespace cyber
}  // namespace apollo
namespace google {
namespace protobuf {
template<> ::apollo::cyber::proto::CyberConfig* Arena::CreateMaybeMessage<::apollo::cyber::proto::CyberConfig>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace apollo {
namespace cyber {
namespace proto {

// ===================================================================

class CyberConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.CyberConfig) */ {
 public:
  CyberConfig();
  virtual ~CyberConfig();

  CyberConfig(const CyberConfig& from);

  inline CyberConfig& operator=(const CyberConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CyberConfig(CyberConfig&& from) noexcept
    : CyberConfig() {
    *this = ::std::move(from);
  }

  inline CyberConfig& operator=(CyberConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CyberConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CyberConfig* internal_default_instance() {
    return reinterpret_cast<const CyberConfig*>(
               &_CyberConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(CyberConfig* other);
  friend void swap(CyberConfig& a, CyberConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CyberConfig* New() const final {
    return CreateMaybeMessage<CyberConfig>(NULL);
  }

  CyberConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CyberConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CyberConfig& from);
  void MergeFrom(const CyberConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CyberConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.cyber.proto.SchedulerConf scheduler_conf = 1;
  bool has_scheduler_conf() const;
  void clear_scheduler_conf();
  static const int kSchedulerConfFieldNumber = 1;
  private:
  const ::apollo::cyber::proto::SchedulerConf& _internal_scheduler_conf() const;
  public:
  const ::apollo::cyber::proto::SchedulerConf& scheduler_conf() const;
  ::apollo::cyber::proto::SchedulerConf* release_scheduler_conf();
  ::apollo::cyber::proto::SchedulerConf* mutable_scheduler_conf();
  void set_allocated_scheduler_conf(::apollo::cyber::proto::SchedulerConf* scheduler_conf);

  // optional .apollo.cyber.proto.TransportConf transport_conf = 2;
  bool has_transport_conf() const;
  void clear_transport_conf();
  static const int kTransportConfFieldNumber = 2;
  private:
  const ::apollo::cyber::proto::TransportConf& _internal_transport_conf() const;
  public:
  const ::apollo::cyber::proto::TransportConf& transport_conf() const;
  ::apollo::cyber::proto::TransportConf* release_transport_conf();
  ::apollo::cyber::proto::TransportConf* mutable_transport_conf();
  void set_allocated_transport_conf(::apollo::cyber::proto::TransportConf* transport_conf);

  // optional .apollo.cyber.proto.RunModeConf run_mode_conf = 3;
  bool has_run_mode_conf() const;
  void clear_run_mode_conf();
  static const int kRunModeConfFieldNumber = 3;
  private:
  const ::apollo::cyber::proto::RunModeConf& _internal_run_mode_conf() const;
  public:
  const ::apollo::cyber::proto::RunModeConf& run_mode_conf() const;
  ::apollo::cyber::proto::RunModeConf* release_run_mode_conf();
  ::apollo::cyber::proto::RunModeConf* mutable_run_mode_conf();
  void set_allocated_run_mode_conf(::apollo::cyber::proto::RunModeConf* run_mode_conf);

  // optional .apollo.cyber.proto.PerfConf perf_conf = 4;
  bool has_perf_conf() const;
  void clear_perf_conf();
  static const int kPerfConfFieldNumber = 4;
  private:
  const ::apollo::cyber::proto::PerfConf& _internal_perf_conf() const;
  public:
  const ::apollo::cyber::proto::PerfConf& perf_conf() const;
  ::apollo::cyber::proto::PerfConf* release_perf_conf();
  ::apollo::cyber::proto::PerfConf* mutable_perf_conf();
  void set_allocated_perf_conf(::apollo::cyber::proto::PerfConf* perf_conf);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.CyberConfig)
 private:
  void set_has_scheduler_conf();
  void clear_has_scheduler_conf();
  void set_has_transport_conf();
  void clear_has_transport_conf();
  void set_has_run_mode_conf();
  void clear_has_run_mode_conf();
  void set_has_perf_conf();
  void clear_has_perf_conf();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::apollo::cyber::proto::SchedulerConf* scheduler_conf_;
  ::apollo::cyber::proto::TransportConf* transport_conf_;
  ::apollo::cyber::proto::RunModeConf* run_mode_conf_;
  ::apollo::cyber::proto::PerfConf* perf_conf_;
  friend struct ::protobuf_cyber_5fconf_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CyberConfig

// optional .apollo.cyber.proto.SchedulerConf scheduler_conf = 1;
inline bool CyberConfig::has_scheduler_conf() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CyberConfig::set_has_scheduler_conf() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CyberConfig::clear_has_scheduler_conf() {
  _has_bits_[0] &= ~0x00000001u;
}
inline const ::apollo::cyber::proto::SchedulerConf& CyberConfig::_internal_scheduler_conf() const {
  return *scheduler_conf_;
}
inline const ::apollo::cyber::proto::SchedulerConf& CyberConfig::scheduler_conf() const {
  const ::apollo::cyber::proto::SchedulerConf* p = scheduler_conf_;
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.CyberConfig.scheduler_conf)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::cyber::proto::SchedulerConf*>(
      &::apollo::cyber::proto::_SchedulerConf_default_instance_);
}
inline ::apollo::cyber::proto::SchedulerConf* CyberConfig::release_scheduler_conf() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.CyberConfig.scheduler_conf)
  clear_has_scheduler_conf();
  ::apollo::cyber::proto::SchedulerConf* temp = scheduler_conf_;
  scheduler_conf_ = NULL;
  return temp;
}
inline ::apollo::cyber::proto::SchedulerConf* CyberConfig::mutable_scheduler_conf() {
  set_has_scheduler_conf();
  if (scheduler_conf_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::cyber::proto::SchedulerConf>(GetArenaNoVirtual());
    scheduler_conf_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.CyberConfig.scheduler_conf)
  return scheduler_conf_;
}
inline void CyberConfig::set_allocated_scheduler_conf(::apollo::cyber::proto::SchedulerConf* scheduler_conf) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(scheduler_conf_);
  }
  if (scheduler_conf) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      scheduler_conf = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, scheduler_conf, submessage_arena);
    }
    set_has_scheduler_conf();
  } else {
    clear_has_scheduler_conf();
  }
  scheduler_conf_ = scheduler_conf;
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.CyberConfig.scheduler_conf)
}

// optional .apollo.cyber.proto.TransportConf transport_conf = 2;
inline bool CyberConfig::has_transport_conf() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CyberConfig::set_has_transport_conf() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CyberConfig::clear_has_transport_conf() {
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::apollo::cyber::proto::TransportConf& CyberConfig::_internal_transport_conf() const {
  return *transport_conf_;
}
inline const ::apollo::cyber::proto::TransportConf& CyberConfig::transport_conf() const {
  const ::apollo::cyber::proto::TransportConf* p = transport_conf_;
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.CyberConfig.transport_conf)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::cyber::proto::TransportConf*>(
      &::apollo::cyber::proto::_TransportConf_default_instance_);
}
inline ::apollo::cyber::proto::TransportConf* CyberConfig::release_transport_conf() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.CyberConfig.transport_conf)
  clear_has_transport_conf();
  ::apollo::cyber::proto::TransportConf* temp = transport_conf_;
  transport_conf_ = NULL;
  return temp;
}
inline ::apollo::cyber::proto::TransportConf* CyberConfig::mutable_transport_conf() {
  set_has_transport_conf();
  if (transport_conf_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::cyber::proto::TransportConf>(GetArenaNoVirtual());
    transport_conf_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.CyberConfig.transport_conf)
  return transport_conf_;
}
inline void CyberConfig::set_allocated_transport_conf(::apollo::cyber::proto::TransportConf* transport_conf) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(transport_conf_);
  }
  if (transport_conf) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      transport_conf = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, transport_conf, submessage_arena);
    }
    set_has_transport_conf();
  } else {
    clear_has_transport_conf();
  }
  transport_conf_ = transport_conf;
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.CyberConfig.transport_conf)
}

// optional .apollo.cyber.proto.RunModeConf run_mode_conf = 3;
inline bool CyberConfig::has_run_mode_conf() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CyberConfig::set_has_run_mode_conf() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CyberConfig::clear_has_run_mode_conf() {
  _has_bits_[0] &= ~0x00000004u;
}
inline const ::apollo::cyber::proto::RunModeConf& CyberConfig::_internal_run_mode_conf() const {
  return *run_mode_conf_;
}
inline const ::apollo::cyber::proto::RunModeConf& CyberConfig::run_mode_conf() const {
  const ::apollo::cyber::proto::RunModeConf* p = run_mode_conf_;
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.CyberConfig.run_mode_conf)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::cyber::proto::RunModeConf*>(
      &::apollo::cyber::proto::_RunModeConf_default_instance_);
}
inline ::apollo::cyber::proto::RunModeConf* CyberConfig::release_run_mode_conf() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.CyberConfig.run_mode_conf)
  clear_has_run_mode_conf();
  ::apollo::cyber::proto::RunModeConf* temp = run_mode_conf_;
  run_mode_conf_ = NULL;
  return temp;
}
inline ::apollo::cyber::proto::RunModeConf* CyberConfig::mutable_run_mode_conf() {
  set_has_run_mode_conf();
  if (run_mode_conf_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::cyber::proto::RunModeConf>(GetArenaNoVirtual());
    run_mode_conf_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.CyberConfig.run_mode_conf)
  return run_mode_conf_;
}
inline void CyberConfig::set_allocated_run_mode_conf(::apollo::cyber::proto::RunModeConf* run_mode_conf) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(run_mode_conf_);
  }
  if (run_mode_conf) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      run_mode_conf = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, run_mode_conf, submessage_arena);
    }
    set_has_run_mode_conf();
  } else {
    clear_has_run_mode_conf();
  }
  run_mode_conf_ = run_mode_conf;
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.CyberConfig.run_mode_conf)
}

// optional .apollo.cyber.proto.PerfConf perf_conf = 4;
inline bool CyberConfig::has_perf_conf() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void CyberConfig::set_has_perf_conf() {
  _has_bits_[0] |= 0x00000008u;
}
inline void CyberConfig::clear_has_perf_conf() {
  _has_bits_[0] &= ~0x00000008u;
}
inline const ::apollo::cyber::proto::PerfConf& CyberConfig::_internal_perf_conf() const {
  return *perf_conf_;
}
inline const ::apollo::cyber::proto::PerfConf& CyberConfig::perf_conf() const {
  const ::apollo::cyber::proto::PerfConf* p = perf_conf_;
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.CyberConfig.perf_conf)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::cyber::proto::PerfConf*>(
      &::apollo::cyber::proto::_PerfConf_default_instance_);
}
inline ::apollo::cyber::proto::PerfConf* CyberConfig::release_perf_conf() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.CyberConfig.perf_conf)
  clear_has_perf_conf();
  ::apollo::cyber::proto::PerfConf* temp = perf_conf_;
  perf_conf_ = NULL;
  return temp;
}
inline ::apollo::cyber::proto::PerfConf* CyberConfig::mutable_perf_conf() {
  set_has_perf_conf();
  if (perf_conf_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::cyber::proto::PerfConf>(GetArenaNoVirtual());
    perf_conf_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.CyberConfig.perf_conf)
  return perf_conf_;
}
inline void CyberConfig::set_allocated_perf_conf(::apollo::cyber::proto::PerfConf* perf_conf) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(perf_conf_);
  }
  if (perf_conf) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      perf_conf = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, perf_conf, submessage_arena);
    }
    set_has_perf_conf();
  } else {
    clear_has_perf_conf();
  }
  perf_conf_ = perf_conf;
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.CyberConfig.perf_conf)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace cyber
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_cyber_5fconf_2eproto
