// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dag_conf.proto

#ifndef PROTOBUF_INCLUDED_dag_5fconf_2eproto
#define PROTOBUF_INCLUDED_dag_5fconf_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "component_conf.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_dag_5fconf_2eproto 

namespace protobuf_dag_5fconf_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[4];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_dag_5fconf_2eproto
namespace apollo {
namespace cyber {
namespace proto {
class ComponentInfo;
class ComponentInfoDefaultTypeInternal;
extern ComponentInfoDefaultTypeInternal _ComponentInfo_default_instance_;
class DagConfig;
class DagConfigDefaultTypeInternal;
extern DagConfigDefaultTypeInternal _DagConfig_default_instance_;
class ModuleConfig;
class ModuleConfigDefaultTypeInternal;
extern ModuleConfigDefaultTypeInternal _ModuleConfig_default_instance_;
class TimerComponentInfo;
class TimerComponentInfoDefaultTypeInternal;
extern TimerComponentInfoDefaultTypeInternal _TimerComponentInfo_default_instance_;
}  // namespace proto
}  // namespace cyber
}  // namespace apollo
namespace google {
namespace protobuf {
template<> ::apollo::cyber::proto::ComponentInfo* Arena::CreateMaybeMessage<::apollo::cyber::proto::ComponentInfo>(Arena*);
template<> ::apollo::cyber::proto::DagConfig* Arena::CreateMaybeMessage<::apollo::cyber::proto::DagConfig>(Arena*);
template<> ::apollo::cyber::proto::ModuleConfig* Arena::CreateMaybeMessage<::apollo::cyber::proto::ModuleConfig>(Arena*);
template<> ::apollo::cyber::proto::TimerComponentInfo* Arena::CreateMaybeMessage<::apollo::cyber::proto::TimerComponentInfo>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace apollo {
namespace cyber {
namespace proto {

// ===================================================================

class ComponentInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.ComponentInfo) */ {
 public:
  ComponentInfo();
  virtual ~ComponentInfo();

  ComponentInfo(const ComponentInfo& from);

  inline ComponentInfo& operator=(const ComponentInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ComponentInfo(ComponentInfo&& from) noexcept
    : ComponentInfo() {
    *this = ::std::move(from);
  }

  inline ComponentInfo& operator=(ComponentInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ComponentInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ComponentInfo* internal_default_instance() {
    return reinterpret_cast<const ComponentInfo*>(
               &_ComponentInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ComponentInfo* other);
  friend void swap(ComponentInfo& a, ComponentInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ComponentInfo* New() const final {
    return CreateMaybeMessage<ComponentInfo>(NULL);
  }

  ComponentInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ComponentInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ComponentInfo& from);
  void MergeFrom(const ComponentInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ComponentInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string class_name = 1;
  bool has_class_name() const;
  void clear_class_name();
  static const int kClassNameFieldNumber = 1;
  const ::std::string& class_name() const;
  void set_class_name(const ::std::string& value);
  #if LANG_CXX11
  void set_class_name(::std::string&& value);
  #endif
  void set_class_name(const char* value);
  void set_class_name(const char* value, size_t size);
  ::std::string* mutable_class_name();
  ::std::string* release_class_name();
  void set_allocated_class_name(::std::string* class_name);

  // optional .apollo.cyber.proto.ComponentConfig config = 2;
  bool has_config() const;
  void clear_config();
  static const int kConfigFieldNumber = 2;
  private:
  const ::apollo::cyber::proto::ComponentConfig& _internal_config() const;
  public:
  const ::apollo::cyber::proto::ComponentConfig& config() const;
  ::apollo::cyber::proto::ComponentConfig* release_config();
  ::apollo::cyber::proto::ComponentConfig* mutable_config();
  void set_allocated_config(::apollo::cyber::proto::ComponentConfig* config);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.ComponentInfo)
 private:
  void set_has_class_name();
  void clear_has_class_name();
  void set_has_config();
  void clear_has_config();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr class_name_;
  ::apollo::cyber::proto::ComponentConfig* config_;
  friend struct ::protobuf_dag_5fconf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TimerComponentInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.TimerComponentInfo) */ {
 public:
  TimerComponentInfo();
  virtual ~TimerComponentInfo();

  TimerComponentInfo(const TimerComponentInfo& from);

  inline TimerComponentInfo& operator=(const TimerComponentInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TimerComponentInfo(TimerComponentInfo&& from) noexcept
    : TimerComponentInfo() {
    *this = ::std::move(from);
  }

  inline TimerComponentInfo& operator=(TimerComponentInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TimerComponentInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TimerComponentInfo* internal_default_instance() {
    return reinterpret_cast<const TimerComponentInfo*>(
               &_TimerComponentInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(TimerComponentInfo* other);
  friend void swap(TimerComponentInfo& a, TimerComponentInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TimerComponentInfo* New() const final {
    return CreateMaybeMessage<TimerComponentInfo>(NULL);
  }

  TimerComponentInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TimerComponentInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TimerComponentInfo& from);
  void MergeFrom(const TimerComponentInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TimerComponentInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string class_name = 1;
  bool has_class_name() const;
  void clear_class_name();
  static const int kClassNameFieldNumber = 1;
  const ::std::string& class_name() const;
  void set_class_name(const ::std::string& value);
  #if LANG_CXX11
  void set_class_name(::std::string&& value);
  #endif
  void set_class_name(const char* value);
  void set_class_name(const char* value, size_t size);
  ::std::string* mutable_class_name();
  ::std::string* release_class_name();
  void set_allocated_class_name(::std::string* class_name);

  // optional .apollo.cyber.proto.TimerComponentConfig config = 2;
  bool has_config() const;
  void clear_config();
  static const int kConfigFieldNumber = 2;
  private:
  const ::apollo::cyber::proto::TimerComponentConfig& _internal_config() const;
  public:
  const ::apollo::cyber::proto::TimerComponentConfig& config() const;
  ::apollo::cyber::proto::TimerComponentConfig* release_config();
  ::apollo::cyber::proto::TimerComponentConfig* mutable_config();
  void set_allocated_config(::apollo::cyber::proto::TimerComponentConfig* config);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.TimerComponentInfo)
 private:
  void set_has_class_name();
  void clear_has_class_name();
  void set_has_config();
  void clear_has_config();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr class_name_;
  ::apollo::cyber::proto::TimerComponentConfig* config_;
  friend struct ::protobuf_dag_5fconf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ModuleConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.ModuleConfig) */ {
 public:
  ModuleConfig();
  virtual ~ModuleConfig();

  ModuleConfig(const ModuleConfig& from);

  inline ModuleConfig& operator=(const ModuleConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ModuleConfig(ModuleConfig&& from) noexcept
    : ModuleConfig() {
    *this = ::std::move(from);
  }

  inline ModuleConfig& operator=(ModuleConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ModuleConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ModuleConfig* internal_default_instance() {
    return reinterpret_cast<const ModuleConfig*>(
               &_ModuleConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(ModuleConfig* other);
  friend void swap(ModuleConfig& a, ModuleConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ModuleConfig* New() const final {
    return CreateMaybeMessage<ModuleConfig>(NULL);
  }

  ModuleConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ModuleConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ModuleConfig& from);
  void MergeFrom(const ModuleConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModuleConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.cyber.proto.ComponentInfo components = 2;
  int components_size() const;
  void clear_components();
  static const int kComponentsFieldNumber = 2;
  ::apollo::cyber::proto::ComponentInfo* mutable_components(int index);
  ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::ComponentInfo >*
      mutable_components();
  const ::apollo::cyber::proto::ComponentInfo& components(int index) const;
  ::apollo::cyber::proto::ComponentInfo* add_components();
  const ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::ComponentInfo >&
      components() const;

  // repeated .apollo.cyber.proto.TimerComponentInfo timer_components = 3;
  int timer_components_size() const;
  void clear_timer_components();
  static const int kTimerComponentsFieldNumber = 3;
  ::apollo::cyber::proto::TimerComponentInfo* mutable_timer_components(int index);
  ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::TimerComponentInfo >*
      mutable_timer_components();
  const ::apollo::cyber::proto::TimerComponentInfo& timer_components(int index) const;
  ::apollo::cyber::proto::TimerComponentInfo* add_timer_components();
  const ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::TimerComponentInfo >&
      timer_components() const;

  // optional string module_library = 1;
  bool has_module_library() const;
  void clear_module_library();
  static const int kModuleLibraryFieldNumber = 1;
  const ::std::string& module_library() const;
  void set_module_library(const ::std::string& value);
  #if LANG_CXX11
  void set_module_library(::std::string&& value);
  #endif
  void set_module_library(const char* value);
  void set_module_library(const char* value, size_t size);
  ::std::string* mutable_module_library();
  ::std::string* release_module_library();
  void set_allocated_module_library(::std::string* module_library);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.ModuleConfig)
 private:
  void set_has_module_library();
  void clear_has_module_library();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::ComponentInfo > components_;
  ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::TimerComponentInfo > timer_components_;
  ::google::protobuf::internal::ArenaStringPtr module_library_;
  friend struct ::protobuf_dag_5fconf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DagConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.DagConfig) */ {
 public:
  DagConfig();
  virtual ~DagConfig();

  DagConfig(const DagConfig& from);

  inline DagConfig& operator=(const DagConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DagConfig(DagConfig&& from) noexcept
    : DagConfig() {
    *this = ::std::move(from);
  }

  inline DagConfig& operator=(DagConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DagConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DagConfig* internal_default_instance() {
    return reinterpret_cast<const DagConfig*>(
               &_DagConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(DagConfig* other);
  friend void swap(DagConfig& a, DagConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DagConfig* New() const final {
    return CreateMaybeMessage<DagConfig>(NULL);
  }

  DagConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DagConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const DagConfig& from);
  void MergeFrom(const DagConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(DagConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.cyber.proto.ModuleConfig module_config = 1;
  int module_config_size() const;
  void clear_module_config();
  static const int kModuleConfigFieldNumber = 1;
  ::apollo::cyber::proto::ModuleConfig* mutable_module_config(int index);
  ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::ModuleConfig >*
      mutable_module_config();
  const ::apollo::cyber::proto::ModuleConfig& module_config(int index) const;
  ::apollo::cyber::proto::ModuleConfig* add_module_config();
  const ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::ModuleConfig >&
      module_config() const;

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.DagConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::ModuleConfig > module_config_;
  friend struct ::protobuf_dag_5fconf_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ComponentInfo

// optional string class_name = 1;
inline bool ComponentInfo::has_class_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ComponentInfo::set_has_class_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ComponentInfo::clear_has_class_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ComponentInfo::clear_class_name() {
  class_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_class_name();
}
inline const ::std::string& ComponentInfo::class_name() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ComponentInfo.class_name)
  return class_name_.GetNoArena();
}
inline void ComponentInfo::set_class_name(const ::std::string& value) {
  set_has_class_name();
  class_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ComponentInfo.class_name)
}
#if LANG_CXX11
inline void ComponentInfo::set_class_name(::std::string&& value) {
  set_has_class_name();
  class_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.ComponentInfo.class_name)
}
#endif
inline void ComponentInfo::set_class_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_class_name();
  class_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.ComponentInfo.class_name)
}
inline void ComponentInfo::set_class_name(const char* value, size_t size) {
  set_has_class_name();
  class_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.ComponentInfo.class_name)
}
inline ::std::string* ComponentInfo::mutable_class_name() {
  set_has_class_name();
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ComponentInfo.class_name)
  return class_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ComponentInfo::release_class_name() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.ComponentInfo.class_name)
  if (!has_class_name()) {
    return NULL;
  }
  clear_has_class_name();
  return class_name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ComponentInfo::set_allocated_class_name(::std::string* class_name) {
  if (class_name != NULL) {
    set_has_class_name();
  } else {
    clear_has_class_name();
  }
  class_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), class_name);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.ComponentInfo.class_name)
}

// optional .apollo.cyber.proto.ComponentConfig config = 2;
inline bool ComponentInfo::has_config() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ComponentInfo::set_has_config() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ComponentInfo::clear_has_config() {
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::apollo::cyber::proto::ComponentConfig& ComponentInfo::_internal_config() const {
  return *config_;
}
inline const ::apollo::cyber::proto::ComponentConfig& ComponentInfo::config() const {
  const ::apollo::cyber::proto::ComponentConfig* p = config_;
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ComponentInfo.config)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::cyber::proto::ComponentConfig*>(
      &::apollo::cyber::proto::_ComponentConfig_default_instance_);
}
inline ::apollo::cyber::proto::ComponentConfig* ComponentInfo::release_config() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.ComponentInfo.config)
  clear_has_config();
  ::apollo::cyber::proto::ComponentConfig* temp = config_;
  config_ = NULL;
  return temp;
}
inline ::apollo::cyber::proto::ComponentConfig* ComponentInfo::mutable_config() {
  set_has_config();
  if (config_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::cyber::proto::ComponentConfig>(GetArenaNoVirtual());
    config_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ComponentInfo.config)
  return config_;
}
inline void ComponentInfo::set_allocated_config(::apollo::cyber::proto::ComponentConfig* config) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(config_);
  }
  if (config) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      config = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, config, submessage_arena);
    }
    set_has_config();
  } else {
    clear_has_config();
  }
  config_ = config;
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.ComponentInfo.config)
}

// -------------------------------------------------------------------

// TimerComponentInfo

// optional string class_name = 1;
inline bool TimerComponentInfo::has_class_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TimerComponentInfo::set_has_class_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TimerComponentInfo::clear_has_class_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TimerComponentInfo::clear_class_name() {
  class_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_class_name();
}
inline const ::std::string& TimerComponentInfo::class_name() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.TimerComponentInfo.class_name)
  return class_name_.GetNoArena();
}
inline void TimerComponentInfo::set_class_name(const ::std::string& value) {
  set_has_class_name();
  class_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.TimerComponentInfo.class_name)
}
#if LANG_CXX11
inline void TimerComponentInfo::set_class_name(::std::string&& value) {
  set_has_class_name();
  class_name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.TimerComponentInfo.class_name)
}
#endif
inline void TimerComponentInfo::set_class_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_class_name();
  class_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.TimerComponentInfo.class_name)
}
inline void TimerComponentInfo::set_class_name(const char* value, size_t size) {
  set_has_class_name();
  class_name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.TimerComponentInfo.class_name)
}
inline ::std::string* TimerComponentInfo::mutable_class_name() {
  set_has_class_name();
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.TimerComponentInfo.class_name)
  return class_name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TimerComponentInfo::release_class_name() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.TimerComponentInfo.class_name)
  if (!has_class_name()) {
    return NULL;
  }
  clear_has_class_name();
  return class_name_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TimerComponentInfo::set_allocated_class_name(::std::string* class_name) {
  if (class_name != NULL) {
    set_has_class_name();
  } else {
    clear_has_class_name();
  }
  class_name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), class_name);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.TimerComponentInfo.class_name)
}

// optional .apollo.cyber.proto.TimerComponentConfig config = 2;
inline bool TimerComponentInfo::has_config() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TimerComponentInfo::set_has_config() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TimerComponentInfo::clear_has_config() {
  _has_bits_[0] &= ~0x00000002u;
}
inline const ::apollo::cyber::proto::TimerComponentConfig& TimerComponentInfo::_internal_config() const {
  return *config_;
}
inline const ::apollo::cyber::proto::TimerComponentConfig& TimerComponentInfo::config() const {
  const ::apollo::cyber::proto::TimerComponentConfig* p = config_;
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.TimerComponentInfo.config)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::cyber::proto::TimerComponentConfig*>(
      &::apollo::cyber::proto::_TimerComponentConfig_default_instance_);
}
inline ::apollo::cyber::proto::TimerComponentConfig* TimerComponentInfo::release_config() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.TimerComponentInfo.config)
  clear_has_config();
  ::apollo::cyber::proto::TimerComponentConfig* temp = config_;
  config_ = NULL;
  return temp;
}
inline ::apollo::cyber::proto::TimerComponentConfig* TimerComponentInfo::mutable_config() {
  set_has_config();
  if (config_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::cyber::proto::TimerComponentConfig>(GetArenaNoVirtual());
    config_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.TimerComponentInfo.config)
  return config_;
}
inline void TimerComponentInfo::set_allocated_config(::apollo::cyber::proto::TimerComponentConfig* config) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(config_);
  }
  if (config) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      config = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, config, submessage_arena);
    }
    set_has_config();
  } else {
    clear_has_config();
  }
  config_ = config;
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.TimerComponentInfo.config)
}

// -------------------------------------------------------------------

// ModuleConfig

// optional string module_library = 1;
inline bool ModuleConfig::has_module_library() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ModuleConfig::set_has_module_library() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ModuleConfig::clear_has_module_library() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ModuleConfig::clear_module_library() {
  module_library_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_module_library();
}
inline const ::std::string& ModuleConfig::module_library() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ModuleConfig.module_library)
  return module_library_.GetNoArena();
}
inline void ModuleConfig::set_module_library(const ::std::string& value) {
  set_has_module_library();
  module_library_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ModuleConfig.module_library)
}
#if LANG_CXX11
inline void ModuleConfig::set_module_library(::std::string&& value) {
  set_has_module_library();
  module_library_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.ModuleConfig.module_library)
}
#endif
inline void ModuleConfig::set_module_library(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_module_library();
  module_library_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.ModuleConfig.module_library)
}
inline void ModuleConfig::set_module_library(const char* value, size_t size) {
  set_has_module_library();
  module_library_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.ModuleConfig.module_library)
}
inline ::std::string* ModuleConfig::mutable_module_library() {
  set_has_module_library();
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ModuleConfig.module_library)
  return module_library_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ModuleConfig::release_module_library() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.ModuleConfig.module_library)
  if (!has_module_library()) {
    return NULL;
  }
  clear_has_module_library();
  return module_library_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ModuleConfig::set_allocated_module_library(::std::string* module_library) {
  if (module_library != NULL) {
    set_has_module_library();
  } else {
    clear_has_module_library();
  }
  module_library_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), module_library);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.ModuleConfig.module_library)
}

// repeated .apollo.cyber.proto.ComponentInfo components = 2;
inline int ModuleConfig::components_size() const {
  return components_.size();
}
inline void ModuleConfig::clear_components() {
  components_.Clear();
}
inline ::apollo::cyber::proto::ComponentInfo* ModuleConfig::mutable_components(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ModuleConfig.components)
  return components_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::ComponentInfo >*
ModuleConfig::mutable_components() {
  // @@protoc_insertion_point(field_mutable_list:apollo.cyber.proto.ModuleConfig.components)
  return &components_;
}
inline const ::apollo::cyber::proto::ComponentInfo& ModuleConfig::components(int index) const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ModuleConfig.components)
  return components_.Get(index);
}
inline ::apollo::cyber::proto::ComponentInfo* ModuleConfig::add_components() {
  // @@protoc_insertion_point(field_add:apollo.cyber.proto.ModuleConfig.components)
  return components_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::ComponentInfo >&
ModuleConfig::components() const {
  // @@protoc_insertion_point(field_list:apollo.cyber.proto.ModuleConfig.components)
  return components_;
}

// repeated .apollo.cyber.proto.TimerComponentInfo timer_components = 3;
inline int ModuleConfig::timer_components_size() const {
  return timer_components_.size();
}
inline void ModuleConfig::clear_timer_components() {
  timer_components_.Clear();
}
inline ::apollo::cyber::proto::TimerComponentInfo* ModuleConfig::mutable_timer_components(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ModuleConfig.timer_components)
  return timer_components_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::TimerComponentInfo >*
ModuleConfig::mutable_timer_components() {
  // @@protoc_insertion_point(field_mutable_list:apollo.cyber.proto.ModuleConfig.timer_components)
  return &timer_components_;
}
inline const ::apollo::cyber::proto::TimerComponentInfo& ModuleConfig::timer_components(int index) const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ModuleConfig.timer_components)
  return timer_components_.Get(index);
}
inline ::apollo::cyber::proto::TimerComponentInfo* ModuleConfig::add_timer_components() {
  // @@protoc_insertion_point(field_add:apollo.cyber.proto.ModuleConfig.timer_components)
  return timer_components_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::TimerComponentInfo >&
ModuleConfig::timer_components() const {
  // @@protoc_insertion_point(field_list:apollo.cyber.proto.ModuleConfig.timer_components)
  return timer_components_;
}

// -------------------------------------------------------------------

// DagConfig

// repeated .apollo.cyber.proto.ModuleConfig module_config = 1;
inline int DagConfig::module_config_size() const {
  return module_config_.size();
}
inline void DagConfig::clear_module_config() {
  module_config_.Clear();
}
inline ::apollo::cyber::proto::ModuleConfig* DagConfig::mutable_module_config(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.DagConfig.module_config)
  return module_config_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::ModuleConfig >*
DagConfig::mutable_module_config() {
  // @@protoc_insertion_point(field_mutable_list:apollo.cyber.proto.DagConfig.module_config)
  return &module_config_;
}
inline const ::apollo::cyber::proto::ModuleConfig& DagConfig::module_config(int index) const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.DagConfig.module_config)
  return module_config_.Get(index);
}
inline ::apollo::cyber::proto::ModuleConfig* DagConfig::add_module_config() {
  // @@protoc_insertion_point(field_add:apollo.cyber.proto.DagConfig.module_config)
  return module_config_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::cyber::proto::ModuleConfig >&
DagConfig::module_config() const {
  // @@protoc_insertion_point(field_list:apollo.cyber.proto.DagConfig.module_config)
  return module_config_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace cyber
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_dag_5fconf_2eproto
