// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: perception.proto

#ifndef PROTOBUF_INCLUDED_perception_2eproto
#define PROTOBUF_INCLUDED_perception_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_perception_2eproto 

namespace protobuf_perception_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_perception_2eproto
namespace apollo {
namespace cyber {
namespace proto {
class Perception;
class PerceptionDefaultTypeInternal;
extern PerceptionDefaultTypeInternal _Perception_default_instance_;
class Perception_Header;
class Perception_HeaderDefaultTypeInternal;
extern Perception_HeaderDefaultTypeInternal _Perception_Header_default_instance_;
}  // namespace proto
}  // namespace cyber
}  // namespace apollo
namespace google {
namespace protobuf {
template<> ::apollo::cyber::proto::Perception* Arena::CreateMaybeMessage<::apollo::cyber::proto::Perception>(Arena*);
template<> ::apollo::cyber::proto::Perception_Header* Arena::CreateMaybeMessage<::apollo::cyber::proto::Perception_Header>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace apollo {
namespace cyber {
namespace proto {

// ===================================================================

class Perception_Header : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.Perception.Header) */ {
 public:
  Perception_Header();
  virtual ~Perception_Header();

  Perception_Header(const Perception_Header& from);

  inline Perception_Header& operator=(const Perception_Header& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Perception_Header(Perception_Header&& from) noexcept
    : Perception_Header() {
    *this = ::std::move(from);
  }

  inline Perception_Header& operator=(Perception_Header&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Perception_Header& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Perception_Header* internal_default_instance() {
    return reinterpret_cast<const Perception_Header*>(
               &_Perception_Header_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Perception_Header* other);
  friend void swap(Perception_Header& a, Perception_Header& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Perception_Header* New() const final {
    return CreateMaybeMessage<Perception_Header>(NULL);
  }

  Perception_Header* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Perception_Header>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Perception_Header& from);
  void MergeFrom(const Perception_Header& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Perception_Header* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 timestamp = 1;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::google::protobuf::uint64 timestamp() const;
  void set_timestamp(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.Perception.Header)
 private:
  void set_has_timestamp();
  void clear_has_timestamp();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint64 timestamp_;
  friend struct ::protobuf_perception_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Perception : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.Perception) */ {
 public:
  Perception();
  virtual ~Perception();

  Perception(const Perception& from);

  inline Perception& operator=(const Perception& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Perception(Perception&& from) noexcept
    : Perception() {
    *this = ::std::move(from);
  }

  inline Perception& operator=(Perception&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Perception& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Perception* internal_default_instance() {
    return reinterpret_cast<const Perception*>(
               &_Perception_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Perception* other);
  friend void swap(Perception& a, Perception& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Perception* New() const final {
    return CreateMaybeMessage<Perception>(NULL);
  }

  Perception* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Perception>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Perception& from);
  void MergeFrom(const Perception& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Perception* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Perception_Header Header;

  // accessors -------------------------------------------------------

  // optional .apollo.cyber.proto.Perception.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  private:
  const ::apollo::cyber::proto::Perception_Header& _internal_header() const;
  public:
  const ::apollo::cyber::proto::Perception_Header& header() const;
  ::apollo::cyber::proto::Perception_Header* release_header();
  ::apollo::cyber::proto::Perception_Header* mutable_header();
  void set_allocated_header(::apollo::cyber::proto::Perception_Header* header);

  // optional uint64 msg_id = 2;
  bool has_msg_id() const;
  void clear_msg_id();
  static const int kMsgIdFieldNumber = 2;
  ::google::protobuf::uint64 msg_id() const;
  void set_msg_id(::google::protobuf::uint64 value);

  // optional double result = 3;
  bool has_result() const;
  void clear_result();
  static const int kResultFieldNumber = 3;
  double result() const;
  void set_result(double value);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.Perception)
 private:
  void set_has_header();
  void clear_has_header();
  void set_has_msg_id();
  void clear_has_msg_id();
  void set_has_result();
  void clear_has_result();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::apollo::cyber::proto::Perception_Header* header_;
  ::google::protobuf::uint64 msg_id_;
  double result_;
  friend struct ::protobuf_perception_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Perception_Header

// optional uint64 timestamp = 1;
inline bool Perception_Header::has_timestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Perception_Header::set_has_timestamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Perception_Header::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Perception_Header::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
  clear_has_timestamp();
}
inline ::google::protobuf::uint64 Perception_Header::timestamp() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Perception.Header.timestamp)
  return timestamp_;
}
inline void Perception_Header::set_timestamp(::google::protobuf::uint64 value) {
  set_has_timestamp();
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Perception.Header.timestamp)
}

// -------------------------------------------------------------------

// Perception

// optional .apollo.cyber.proto.Perception.Header header = 1;
inline bool Perception::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Perception::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Perception::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Perception::clear_header() {
  if (header_ != NULL) header_->Clear();
  clear_has_header();
}
inline const ::apollo::cyber::proto::Perception_Header& Perception::_internal_header() const {
  return *header_;
}
inline const ::apollo::cyber::proto::Perception_Header& Perception::header() const {
  const ::apollo::cyber::proto::Perception_Header* p = header_;
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Perception.header)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::cyber::proto::Perception_Header*>(
      &::apollo::cyber::proto::_Perception_Header_default_instance_);
}
inline ::apollo::cyber::proto::Perception_Header* Perception::release_header() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.Perception.header)
  clear_has_header();
  ::apollo::cyber::proto::Perception_Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::apollo::cyber::proto::Perception_Header* Perception::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::cyber::proto::Perception_Header>(GetArenaNoVirtual());
    header_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.Perception.header)
  return header_;
}
inline void Perception::set_allocated_header(::apollo::cyber::proto::Perception_Header* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete header_;
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    set_has_header();
  } else {
    clear_has_header();
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.Perception.header)
}

// optional uint64 msg_id = 2;
inline bool Perception::has_msg_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Perception::set_has_msg_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Perception::clear_has_msg_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Perception::clear_msg_id() {
  msg_id_ = GOOGLE_ULONGLONG(0);
  clear_has_msg_id();
}
inline ::google::protobuf::uint64 Perception::msg_id() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Perception.msg_id)
  return msg_id_;
}
inline void Perception::set_msg_id(::google::protobuf::uint64 value) {
  set_has_msg_id();
  msg_id_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Perception.msg_id)
}

// optional double result = 3;
inline bool Perception::has_result() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Perception::set_has_result() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Perception::clear_has_result() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Perception::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline double Perception::result() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.Perception.result)
  return result_;
}
inline void Perception::set_result(double value) {
  set_has_result();
  result_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.Perception.result)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace cyber
}  // namespace apollo

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_perception_2eproto
