// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: run_mode_conf.proto

#ifndef PROTOBUF_INCLUDED_run_5fmode_5fconf_2eproto
#define PROTOBUF_INCLUDED_run_5fmode_5fconf_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_run_5fmode_5fconf_2eproto 

namespace protobuf_run_5fmode_5fconf_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_run_5fmode_5fconf_2eproto
namespace apollo {
namespace cyber {
namespace proto {
class RunModeConf;
class RunModeConfDefaultTypeInternal;
extern RunModeConfDefaultTypeInternal _RunModeConf_default_instance_;
}  // namespace proto
}  // namespace cyber
}  // namespace apollo
namespace google {
namespace protobuf {
template<> ::apollo::cyber::proto::RunModeConf* Arena::CreateMaybeMessage<::apollo::cyber::proto::RunModeConf>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace apollo {
namespace cyber {
namespace proto {

enum RunMode {
  MODE_REALITY = 0,
  MODE_SIMULATION = 1
};
bool RunMode_IsValid(int value);
const RunMode RunMode_MIN = MODE_REALITY;
const RunMode RunMode_MAX = MODE_SIMULATION;
const int RunMode_ARRAYSIZE = RunMode_MAX + 1;

const ::google::protobuf::EnumDescriptor* RunMode_descriptor();
inline const ::std::string& RunMode_Name(RunMode value) {
  return ::google::protobuf::internal::NameOfEnum(
    RunMode_descriptor(), value);
}
inline bool RunMode_Parse(
    const ::std::string& name, RunMode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RunMode>(
    RunMode_descriptor(), name, value);
}
// ===================================================================

class RunModeConf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.RunModeConf) */ {
 public:
  RunModeConf();
  virtual ~RunModeConf();

  RunModeConf(const RunModeConf& from);

  inline RunModeConf& operator=(const RunModeConf& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RunModeConf(RunModeConf&& from) noexcept
    : RunModeConf() {
    *this = ::std::move(from);
  }

  inline RunModeConf& operator=(RunModeConf&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RunModeConf& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RunModeConf* internal_default_instance() {
    return reinterpret_cast<const RunModeConf*>(
               &_RunModeConf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(RunModeConf* other);
  friend void swap(RunModeConf& a, RunModeConf& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RunModeConf* New() const final {
    return CreateMaybeMessage<RunModeConf>(NULL);
  }

  RunModeConf* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RunModeConf>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RunModeConf& from);
  void MergeFrom(const RunModeConf& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RunModeConf* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.cyber.proto.RunMode run_mode = 1 [default = MODE_REALITY];
  bool has_run_mode() const;
  void clear_run_mode();
  static const int kRunModeFieldNumber = 1;
  ::apollo::cyber::proto::RunMode run_mode() const;
  void set_run_mode(::apollo::cyber::proto::RunMode value);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.RunModeConf)
 private:
  void set_has_run_mode();
  void clear_has_run_mode();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  int run_mode_;
  friend struct ::protobuf_run_5fmode_5fconf_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RunModeConf

// optional .apollo.cyber.proto.RunMode run_mode = 1 [default = MODE_REALITY];
inline bool RunModeConf::has_run_mode() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RunModeConf::set_has_run_mode() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RunModeConf::clear_has_run_mode() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RunModeConf::clear_run_mode() {
  run_mode_ = 0;
  clear_has_run_mode();
}
inline ::apollo::cyber::proto::RunMode RunModeConf::run_mode() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.RunModeConf.run_mode)
  return static_cast< ::apollo::cyber::proto::RunMode >(run_mode_);
}
inline void RunModeConf::set_run_mode(::apollo::cyber::proto::RunMode value) {
  assert(::apollo::cyber::proto::RunMode_IsValid(value));
  set_has_run_mode();
  run_mode_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.RunModeConf.run_mode)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace cyber
}  // namespace apollo

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::apollo::cyber::proto::RunMode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::cyber::proto::RunMode>() {
  return ::apollo::cyber::proto::RunMode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_run_5fmode_5fconf_2eproto
