// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transport_conf.proto

#ifndef PROTOBUF_INCLUDED_transport_5fconf_2eproto
#define PROTOBUF_INCLUDED_transport_5fconf_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_transport_5fconf_2eproto 

namespace protobuf_transport_5fconf_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[6];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_transport_5fconf_2eproto
namespace apollo {
namespace cyber {
namespace proto {
class CommunicationMode;
class CommunicationModeDefaultTypeInternal;
extern CommunicationModeDefaultTypeInternal _CommunicationMode_default_instance_;
class ResourceLimit;
class ResourceLimitDefaultTypeInternal;
extern ResourceLimitDefaultTypeInternal _ResourceLimit_default_instance_;
class RtpsParticipantAttr;
class RtpsParticipantAttrDefaultTypeInternal;
extern RtpsParticipantAttrDefaultTypeInternal _RtpsParticipantAttr_default_instance_;
class ShmConf;
class ShmConfDefaultTypeInternal;
extern ShmConfDefaultTypeInternal _ShmConf_default_instance_;
class ShmMulticastLocator;
class ShmMulticastLocatorDefaultTypeInternal;
extern ShmMulticastLocatorDefaultTypeInternal _ShmMulticastLocator_default_instance_;
class TransportConf;
class TransportConfDefaultTypeInternal;
extern TransportConfDefaultTypeInternal _TransportConf_default_instance_;
}  // namespace proto
}  // namespace cyber
}  // namespace apollo
namespace google {
namespace protobuf {
template<> ::apollo::cyber::proto::CommunicationMode* Arena::CreateMaybeMessage<::apollo::cyber::proto::CommunicationMode>(Arena*);
template<> ::apollo::cyber::proto::ResourceLimit* Arena::CreateMaybeMessage<::apollo::cyber::proto::ResourceLimit>(Arena*);
template<> ::apollo::cyber::proto::RtpsParticipantAttr* Arena::CreateMaybeMessage<::apollo::cyber::proto::RtpsParticipantAttr>(Arena*);
template<> ::apollo::cyber::proto::ShmConf* Arena::CreateMaybeMessage<::apollo::cyber::proto::ShmConf>(Arena*);
template<> ::apollo::cyber::proto::ShmMulticastLocator* Arena::CreateMaybeMessage<::apollo::cyber::proto::ShmMulticastLocator>(Arena*);
template<> ::apollo::cyber::proto::TransportConf* Arena::CreateMaybeMessage<::apollo::cyber::proto::TransportConf>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace apollo {
namespace cyber {
namespace proto {

enum OptionalMode {
  HYBRID = 0,
  INTRA = 1,
  SHM = 2,
  RTPS = 3
};
bool OptionalMode_IsValid(int value);
const OptionalMode OptionalMode_MIN = HYBRID;
const OptionalMode OptionalMode_MAX = RTPS;
const int OptionalMode_ARRAYSIZE = OptionalMode_MAX + 1;

const ::google::protobuf::EnumDescriptor* OptionalMode_descriptor();
inline const ::std::string& OptionalMode_Name(OptionalMode value) {
  return ::google::protobuf::internal::NameOfEnum(
    OptionalMode_descriptor(), value);
}
inline bool OptionalMode_Parse(
    const ::std::string& name, OptionalMode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<OptionalMode>(
    OptionalMode_descriptor(), name, value);
}
// ===================================================================

class ShmMulticastLocator : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.ShmMulticastLocator) */ {
 public:
  ShmMulticastLocator();
  virtual ~ShmMulticastLocator();

  ShmMulticastLocator(const ShmMulticastLocator& from);

  inline ShmMulticastLocator& operator=(const ShmMulticastLocator& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ShmMulticastLocator(ShmMulticastLocator&& from) noexcept
    : ShmMulticastLocator() {
    *this = ::std::move(from);
  }

  inline ShmMulticastLocator& operator=(ShmMulticastLocator&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ShmMulticastLocator& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ShmMulticastLocator* internal_default_instance() {
    return reinterpret_cast<const ShmMulticastLocator*>(
               &_ShmMulticastLocator_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ShmMulticastLocator* other);
  friend void swap(ShmMulticastLocator& a, ShmMulticastLocator& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ShmMulticastLocator* New() const final {
    return CreateMaybeMessage<ShmMulticastLocator>(NULL);
  }

  ShmMulticastLocator* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ShmMulticastLocator>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ShmMulticastLocator& from);
  void MergeFrom(const ShmMulticastLocator& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ShmMulticastLocator* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string ip = 1;
  bool has_ip() const;
  void clear_ip();
  static const int kIpFieldNumber = 1;
  const ::std::string& ip() const;
  void set_ip(const ::std::string& value);
  #if LANG_CXX11
  void set_ip(::std::string&& value);
  #endif
  void set_ip(const char* value);
  void set_ip(const char* value, size_t size);
  ::std::string* mutable_ip();
  ::std::string* release_ip();
  void set_allocated_ip(::std::string* ip);

  // optional uint32 port = 2;
  bool has_port() const;
  void clear_port();
  static const int kPortFieldNumber = 2;
  ::google::protobuf::uint32 port() const;
  void set_port(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.ShmMulticastLocator)
 private:
  void set_has_ip();
  void clear_has_ip();
  void set_has_port();
  void clear_has_port();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr ip_;
  ::google::protobuf::uint32 port_;
  friend struct ::protobuf_transport_5fconf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ShmConf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.ShmConf) */ {
 public:
  ShmConf();
  virtual ~ShmConf();

  ShmConf(const ShmConf& from);

  inline ShmConf& operator=(const ShmConf& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ShmConf(ShmConf&& from) noexcept
    : ShmConf() {
    *this = ::std::move(from);
  }

  inline ShmConf& operator=(ShmConf&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ShmConf& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ShmConf* internal_default_instance() {
    return reinterpret_cast<const ShmConf*>(
               &_ShmConf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ShmConf* other);
  friend void swap(ShmConf& a, ShmConf& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ShmConf* New() const final {
    return CreateMaybeMessage<ShmConf>(NULL);
  }

  ShmConf* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ShmConf>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ShmConf& from);
  void MergeFrom(const ShmConf& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ShmConf* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string notifier_type = 1;
  bool has_notifier_type() const;
  void clear_notifier_type();
  static const int kNotifierTypeFieldNumber = 1;
  const ::std::string& notifier_type() const;
  void set_notifier_type(const ::std::string& value);
  #if LANG_CXX11
  void set_notifier_type(::std::string&& value);
  #endif
  void set_notifier_type(const char* value);
  void set_notifier_type(const char* value, size_t size);
  ::std::string* mutable_notifier_type();
  ::std::string* release_notifier_type();
  void set_allocated_notifier_type(::std::string* notifier_type);

  // optional string shm_type = 2;
  bool has_shm_type() const;
  void clear_shm_type();
  static const int kShmTypeFieldNumber = 2;
  const ::std::string& shm_type() const;
  void set_shm_type(const ::std::string& value);
  #if LANG_CXX11
  void set_shm_type(::std::string&& value);
  #endif
  void set_shm_type(const char* value);
  void set_shm_type(const char* value, size_t size);
  ::std::string* mutable_shm_type();
  ::std::string* release_shm_type();
  void set_allocated_shm_type(::std::string* shm_type);

  // optional .apollo.cyber.proto.ShmMulticastLocator shm_locator = 3;
  bool has_shm_locator() const;
  void clear_shm_locator();
  static const int kShmLocatorFieldNumber = 3;
  private:
  const ::apollo::cyber::proto::ShmMulticastLocator& _internal_shm_locator() const;
  public:
  const ::apollo::cyber::proto::ShmMulticastLocator& shm_locator() const;
  ::apollo::cyber::proto::ShmMulticastLocator* release_shm_locator();
  ::apollo::cyber::proto::ShmMulticastLocator* mutable_shm_locator();
  void set_allocated_shm_locator(::apollo::cyber::proto::ShmMulticastLocator* shm_locator);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.ShmConf)
 private:
  void set_has_notifier_type();
  void clear_has_notifier_type();
  void set_has_shm_type();
  void clear_has_shm_type();
  void set_has_shm_locator();
  void clear_has_shm_locator();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr notifier_type_;
  ::google::protobuf::internal::ArenaStringPtr shm_type_;
  ::apollo::cyber::proto::ShmMulticastLocator* shm_locator_;
  friend struct ::protobuf_transport_5fconf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RtpsParticipantAttr : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.RtpsParticipantAttr) */ {
 public:
  RtpsParticipantAttr();
  virtual ~RtpsParticipantAttr();

  RtpsParticipantAttr(const RtpsParticipantAttr& from);

  inline RtpsParticipantAttr& operator=(const RtpsParticipantAttr& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RtpsParticipantAttr(RtpsParticipantAttr&& from) noexcept
    : RtpsParticipantAttr() {
    *this = ::std::move(from);
  }

  inline RtpsParticipantAttr& operator=(RtpsParticipantAttr&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RtpsParticipantAttr& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RtpsParticipantAttr* internal_default_instance() {
    return reinterpret_cast<const RtpsParticipantAttr*>(
               &_RtpsParticipantAttr_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(RtpsParticipantAttr* other);
  friend void swap(RtpsParticipantAttr& a, RtpsParticipantAttr& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RtpsParticipantAttr* New() const final {
    return CreateMaybeMessage<RtpsParticipantAttr>(NULL);
  }

  RtpsParticipantAttr* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RtpsParticipantAttr>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RtpsParticipantAttr& from);
  void MergeFrom(const RtpsParticipantAttr& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RtpsParticipantAttr* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 lease_duration = 1 [default = 12];
  bool has_lease_duration() const;
  void clear_lease_duration();
  static const int kLeaseDurationFieldNumber = 1;
  ::google::protobuf::int32 lease_duration() const;
  void set_lease_duration(::google::protobuf::int32 value);

  // optional int32 announcement_period = 2 [default = 3];
  bool has_announcement_period() const;
  void clear_announcement_period();
  static const int kAnnouncementPeriodFieldNumber = 2;
  ::google::protobuf::int32 announcement_period() const;
  void set_announcement_period(::google::protobuf::int32 value);

  // optional uint32 domain_id_gain = 3 [default = 200];
  bool has_domain_id_gain() const;
  void clear_domain_id_gain();
  static const int kDomainIdGainFieldNumber = 3;
  ::google::protobuf::uint32 domain_id_gain() const;
  void set_domain_id_gain(::google::protobuf::uint32 value);

  // optional uint32 port_base = 4 [default = 10000];
  bool has_port_base() const;
  void clear_port_base();
  static const int kPortBaseFieldNumber = 4;
  ::google::protobuf::uint32 port_base() const;
  void set_port_base(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.RtpsParticipantAttr)
 private:
  void set_has_lease_duration();
  void clear_has_lease_duration();
  void set_has_announcement_period();
  void clear_has_announcement_period();
  void set_has_domain_id_gain();
  void clear_has_domain_id_gain();
  void set_has_port_base();
  void clear_has_port_base();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::int32 lease_duration_;
  ::google::protobuf::int32 announcement_period_;
  ::google::protobuf::uint32 domain_id_gain_;
  ::google::protobuf::uint32 port_base_;
  friend struct ::protobuf_transport_5fconf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class CommunicationMode : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.CommunicationMode) */ {
 public:
  CommunicationMode();
  virtual ~CommunicationMode();

  CommunicationMode(const CommunicationMode& from);

  inline CommunicationMode& operator=(const CommunicationMode& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CommunicationMode(CommunicationMode&& from) noexcept
    : CommunicationMode() {
    *this = ::std::move(from);
  }

  inline CommunicationMode& operator=(CommunicationMode&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CommunicationMode& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CommunicationMode* internal_default_instance() {
    return reinterpret_cast<const CommunicationMode*>(
               &_CommunicationMode_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(CommunicationMode* other);
  friend void swap(CommunicationMode& a, CommunicationMode& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CommunicationMode* New() const final {
    return CreateMaybeMessage<CommunicationMode>(NULL);
  }

  CommunicationMode* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<CommunicationMode>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const CommunicationMode& from);
  void MergeFrom(const CommunicationMode& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CommunicationMode* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.cyber.proto.OptionalMode diff_host = 3 [default = RTPS];
  bool has_diff_host() const;
  void clear_diff_host();
  static const int kDiffHostFieldNumber = 3;
  ::apollo::cyber::proto::OptionalMode diff_host() const;
  void set_diff_host(::apollo::cyber::proto::OptionalMode value);

  // optional .apollo.cyber.proto.OptionalMode same_proc = 1 [default = INTRA];
  bool has_same_proc() const;
  void clear_same_proc();
  static const int kSameProcFieldNumber = 1;
  ::apollo::cyber::proto::OptionalMode same_proc() const;
  void set_same_proc(::apollo::cyber::proto::OptionalMode value);

  // optional .apollo.cyber.proto.OptionalMode diff_proc = 2 [default = SHM];
  bool has_diff_proc() const;
  void clear_diff_proc();
  static const int kDiffProcFieldNumber = 2;
  ::apollo::cyber::proto::OptionalMode diff_proc() const;
  void set_diff_proc(::apollo::cyber::proto::OptionalMode value);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.CommunicationMode)
 private:
  void set_has_same_proc();
  void clear_has_same_proc();
  void set_has_diff_proc();
  void clear_has_diff_proc();
  void set_has_diff_host();
  void clear_has_diff_host();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  int diff_host_;
  int same_proc_;
  int diff_proc_;
  friend struct ::protobuf_transport_5fconf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ResourceLimit : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.ResourceLimit) */ {
 public:
  ResourceLimit();
  virtual ~ResourceLimit();

  ResourceLimit(const ResourceLimit& from);

  inline ResourceLimit& operator=(const ResourceLimit& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ResourceLimit(ResourceLimit&& from) noexcept
    : ResourceLimit() {
    *this = ::std::move(from);
  }

  inline ResourceLimit& operator=(ResourceLimit&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResourceLimit& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ResourceLimit* internal_default_instance() {
    return reinterpret_cast<const ResourceLimit*>(
               &_ResourceLimit_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(ResourceLimit* other);
  friend void swap(ResourceLimit& a, ResourceLimit& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ResourceLimit* New() const final {
    return CreateMaybeMessage<ResourceLimit>(NULL);
  }

  ResourceLimit* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ResourceLimit>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ResourceLimit& from);
  void MergeFrom(const ResourceLimit& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResourceLimit* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 max_history_depth = 1 [default = 1000];
  bool has_max_history_depth() const;
  void clear_max_history_depth();
  static const int kMaxHistoryDepthFieldNumber = 1;
  ::google::protobuf::uint32 max_history_depth() const;
  void set_max_history_depth(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.ResourceLimit)
 private:
  void set_has_max_history_depth();
  void clear_has_max_history_depth();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 max_history_depth_;
  friend struct ::protobuf_transport_5fconf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class TransportConf : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.cyber.proto.TransportConf) */ {
 public:
  TransportConf();
  virtual ~TransportConf();

  TransportConf(const TransportConf& from);

  inline TransportConf& operator=(const TransportConf& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TransportConf(TransportConf&& from) noexcept
    : TransportConf() {
    *this = ::std::move(from);
  }

  inline TransportConf& operator=(TransportConf&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TransportConf& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TransportConf* internal_default_instance() {
    return reinterpret_cast<const TransportConf*>(
               &_TransportConf_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(TransportConf* other);
  friend void swap(TransportConf& a, TransportConf& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TransportConf* New() const final {
    return CreateMaybeMessage<TransportConf>(NULL);
  }

  TransportConf* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TransportConf>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TransportConf& from);
  void MergeFrom(const TransportConf& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TransportConf* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.cyber.proto.ShmConf shm_conf = 1;
  bool has_shm_conf() const;
  void clear_shm_conf();
  static const int kShmConfFieldNumber = 1;
  private:
  const ::apollo::cyber::proto::ShmConf& _internal_shm_conf() const;
  public:
  const ::apollo::cyber::proto::ShmConf& shm_conf() const;
  ::apollo::cyber::proto::ShmConf* release_shm_conf();
  ::apollo::cyber::proto::ShmConf* mutable_shm_conf();
  void set_allocated_shm_conf(::apollo::cyber::proto::ShmConf* shm_conf);

  // optional .apollo.cyber.proto.RtpsParticipantAttr participant_attr = 2;
  bool has_participant_attr() const;
  void clear_participant_attr();
  static const int kParticipantAttrFieldNumber = 2;
  private:
  const ::apollo::cyber::proto::RtpsParticipantAttr& _internal_participant_attr() const;
  public:
  const ::apollo::cyber::proto::RtpsParticipantAttr& participant_attr() const;
  ::apollo::cyber::proto::RtpsParticipantAttr* release_participant_attr();
  ::apollo::cyber::proto::RtpsParticipantAttr* mutable_participant_attr();
  void set_allocated_participant_attr(::apollo::cyber::proto::RtpsParticipantAttr* participant_attr);

  // optional .apollo.cyber.proto.CommunicationMode communication_mode = 3;
  bool has_communication_mode() const;
  void clear_communication_mode();
  static const int kCommunicationModeFieldNumber = 3;
  private:
  const ::apollo::cyber::proto::CommunicationMode& _internal_communication_mode() const;
  public:
  const ::apollo::cyber::proto::CommunicationMode& communication_mode() const;
  ::apollo::cyber::proto::CommunicationMode* release_communication_mode();
  ::apollo::cyber::proto::CommunicationMode* mutable_communication_mode();
  void set_allocated_communication_mode(::apollo::cyber::proto::CommunicationMode* communication_mode);

  // optional .apollo.cyber.proto.ResourceLimit resource_limit = 4;
  bool has_resource_limit() const;
  void clear_resource_limit();
  static const int kResourceLimitFieldNumber = 4;
  private:
  const ::apollo::cyber::proto::ResourceLimit& _internal_resource_limit() const;
  public:
  const ::apollo::cyber::proto::ResourceLimit& resource_limit() const;
  ::apollo::cyber::proto::ResourceLimit* release_resource_limit();
  ::apollo::cyber::proto::ResourceLimit* mutable_resource_limit();
  void set_allocated_resource_limit(::apollo::cyber::proto::ResourceLimit* resource_limit);

  // @@protoc_insertion_point(class_scope:apollo.cyber.proto.TransportConf)
 private:
  void set_has_shm_conf();
  void clear_has_shm_conf();
  void set_has_participant_attr();
  void clear_has_participant_attr();
  void set_has_communication_mode();
  void clear_has_communication_mode();
  void set_has_resource_limit();
  void clear_has_resource_limit();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::apollo::cyber::proto::ShmConf* shm_conf_;
  ::apollo::cyber::proto::RtpsParticipantAttr* participant_attr_;
  ::apollo::cyber::proto::CommunicationMode* communication_mode_;
  ::apollo::cyber::proto::ResourceLimit* resource_limit_;
  friend struct ::protobuf_transport_5fconf_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ShmMulticastLocator

// optional string ip = 1;
inline bool ShmMulticastLocator::has_ip() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ShmMulticastLocator::set_has_ip() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ShmMulticastLocator::clear_has_ip() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ShmMulticastLocator::clear_ip() {
  ip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_ip();
}
inline const ::std::string& ShmMulticastLocator::ip() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ShmMulticastLocator.ip)
  return ip_.GetNoArena();
}
inline void ShmMulticastLocator::set_ip(const ::std::string& value) {
  set_has_ip();
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ShmMulticastLocator.ip)
}
#if LANG_CXX11
inline void ShmMulticastLocator::set_ip(::std::string&& value) {
  set_has_ip();
  ip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.ShmMulticastLocator.ip)
}
#endif
inline void ShmMulticastLocator::set_ip(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_ip();
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.ShmMulticastLocator.ip)
}
inline void ShmMulticastLocator::set_ip(const char* value, size_t size) {
  set_has_ip();
  ip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.ShmMulticastLocator.ip)
}
inline ::std::string* ShmMulticastLocator::mutable_ip() {
  set_has_ip();
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ShmMulticastLocator.ip)
  return ip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ShmMulticastLocator::release_ip() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.ShmMulticastLocator.ip)
  if (!has_ip()) {
    return NULL;
  }
  clear_has_ip();
  return ip_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ShmMulticastLocator::set_allocated_ip(::std::string* ip) {
  if (ip != NULL) {
    set_has_ip();
  } else {
    clear_has_ip();
  }
  ip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ip);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.ShmMulticastLocator.ip)
}

// optional uint32 port = 2;
inline bool ShmMulticastLocator::has_port() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ShmMulticastLocator::set_has_port() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ShmMulticastLocator::clear_has_port() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ShmMulticastLocator::clear_port() {
  port_ = 0u;
  clear_has_port();
}
inline ::google::protobuf::uint32 ShmMulticastLocator::port() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ShmMulticastLocator.port)
  return port_;
}
inline void ShmMulticastLocator::set_port(::google::protobuf::uint32 value) {
  set_has_port();
  port_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ShmMulticastLocator.port)
}

// -------------------------------------------------------------------

// ShmConf

// optional string notifier_type = 1;
inline bool ShmConf::has_notifier_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ShmConf::set_has_notifier_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ShmConf::clear_has_notifier_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ShmConf::clear_notifier_type() {
  notifier_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_notifier_type();
}
inline const ::std::string& ShmConf::notifier_type() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ShmConf.notifier_type)
  return notifier_type_.GetNoArena();
}
inline void ShmConf::set_notifier_type(const ::std::string& value) {
  set_has_notifier_type();
  notifier_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ShmConf.notifier_type)
}
#if LANG_CXX11
inline void ShmConf::set_notifier_type(::std::string&& value) {
  set_has_notifier_type();
  notifier_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.ShmConf.notifier_type)
}
#endif
inline void ShmConf::set_notifier_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_notifier_type();
  notifier_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.ShmConf.notifier_type)
}
inline void ShmConf::set_notifier_type(const char* value, size_t size) {
  set_has_notifier_type();
  notifier_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.ShmConf.notifier_type)
}
inline ::std::string* ShmConf::mutable_notifier_type() {
  set_has_notifier_type();
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ShmConf.notifier_type)
  return notifier_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ShmConf::release_notifier_type() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.ShmConf.notifier_type)
  if (!has_notifier_type()) {
    return NULL;
  }
  clear_has_notifier_type();
  return notifier_type_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ShmConf::set_allocated_notifier_type(::std::string* notifier_type) {
  if (notifier_type != NULL) {
    set_has_notifier_type();
  } else {
    clear_has_notifier_type();
  }
  notifier_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), notifier_type);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.ShmConf.notifier_type)
}

// optional string shm_type = 2;
inline bool ShmConf::has_shm_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ShmConf::set_has_shm_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ShmConf::clear_has_shm_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ShmConf::clear_shm_type() {
  shm_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_shm_type();
}
inline const ::std::string& ShmConf::shm_type() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ShmConf.shm_type)
  return shm_type_.GetNoArena();
}
inline void ShmConf::set_shm_type(const ::std::string& value) {
  set_has_shm_type();
  shm_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ShmConf.shm_type)
}
#if LANG_CXX11
inline void ShmConf::set_shm_type(::std::string&& value) {
  set_has_shm_type();
  shm_type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:apollo.cyber.proto.ShmConf.shm_type)
}
#endif
inline void ShmConf::set_shm_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_shm_type();
  shm_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.cyber.proto.ShmConf.shm_type)
}
inline void ShmConf::set_shm_type(const char* value, size_t size) {
  set_has_shm_type();
  shm_type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.cyber.proto.ShmConf.shm_type)
}
inline ::std::string* ShmConf::mutable_shm_type() {
  set_has_shm_type();
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ShmConf.shm_type)
  return shm_type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ShmConf::release_shm_type() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.ShmConf.shm_type)
  if (!has_shm_type()) {
    return NULL;
  }
  clear_has_shm_type();
  return shm_type_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ShmConf::set_allocated_shm_type(::std::string* shm_type) {
  if (shm_type != NULL) {
    set_has_shm_type();
  } else {
    clear_has_shm_type();
  }
  shm_type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), shm_type);
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.ShmConf.shm_type)
}

// optional .apollo.cyber.proto.ShmMulticastLocator shm_locator = 3;
inline bool ShmConf::has_shm_locator() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ShmConf::set_has_shm_locator() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ShmConf::clear_has_shm_locator() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ShmConf::clear_shm_locator() {
  if (shm_locator_ != NULL) shm_locator_->Clear();
  clear_has_shm_locator();
}
inline const ::apollo::cyber::proto::ShmMulticastLocator& ShmConf::_internal_shm_locator() const {
  return *shm_locator_;
}
inline const ::apollo::cyber::proto::ShmMulticastLocator& ShmConf::shm_locator() const {
  const ::apollo::cyber::proto::ShmMulticastLocator* p = shm_locator_;
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ShmConf.shm_locator)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::cyber::proto::ShmMulticastLocator*>(
      &::apollo::cyber::proto::_ShmMulticastLocator_default_instance_);
}
inline ::apollo::cyber::proto::ShmMulticastLocator* ShmConf::release_shm_locator() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.ShmConf.shm_locator)
  clear_has_shm_locator();
  ::apollo::cyber::proto::ShmMulticastLocator* temp = shm_locator_;
  shm_locator_ = NULL;
  return temp;
}
inline ::apollo::cyber::proto::ShmMulticastLocator* ShmConf::mutable_shm_locator() {
  set_has_shm_locator();
  if (shm_locator_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::cyber::proto::ShmMulticastLocator>(GetArenaNoVirtual());
    shm_locator_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.ShmConf.shm_locator)
  return shm_locator_;
}
inline void ShmConf::set_allocated_shm_locator(::apollo::cyber::proto::ShmMulticastLocator* shm_locator) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete shm_locator_;
  }
  if (shm_locator) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      shm_locator = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, shm_locator, submessage_arena);
    }
    set_has_shm_locator();
  } else {
    clear_has_shm_locator();
  }
  shm_locator_ = shm_locator;
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.ShmConf.shm_locator)
}

// -------------------------------------------------------------------

// RtpsParticipantAttr

// optional int32 lease_duration = 1 [default = 12];
inline bool RtpsParticipantAttr::has_lease_duration() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RtpsParticipantAttr::set_has_lease_duration() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RtpsParticipantAttr::clear_has_lease_duration() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RtpsParticipantAttr::clear_lease_duration() {
  lease_duration_ = 12;
  clear_has_lease_duration();
}
inline ::google::protobuf::int32 RtpsParticipantAttr::lease_duration() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.RtpsParticipantAttr.lease_duration)
  return lease_duration_;
}
inline void RtpsParticipantAttr::set_lease_duration(::google::protobuf::int32 value) {
  set_has_lease_duration();
  lease_duration_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.RtpsParticipantAttr.lease_duration)
}

// optional int32 announcement_period = 2 [default = 3];
inline bool RtpsParticipantAttr::has_announcement_period() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RtpsParticipantAttr::set_has_announcement_period() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RtpsParticipantAttr::clear_has_announcement_period() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RtpsParticipantAttr::clear_announcement_period() {
  announcement_period_ = 3;
  clear_has_announcement_period();
}
inline ::google::protobuf::int32 RtpsParticipantAttr::announcement_period() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.RtpsParticipantAttr.announcement_period)
  return announcement_period_;
}
inline void RtpsParticipantAttr::set_announcement_period(::google::protobuf::int32 value) {
  set_has_announcement_period();
  announcement_period_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.RtpsParticipantAttr.announcement_period)
}

// optional uint32 domain_id_gain = 3 [default = 200];
inline bool RtpsParticipantAttr::has_domain_id_gain() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RtpsParticipantAttr::set_has_domain_id_gain() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RtpsParticipantAttr::clear_has_domain_id_gain() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RtpsParticipantAttr::clear_domain_id_gain() {
  domain_id_gain_ = 200u;
  clear_has_domain_id_gain();
}
inline ::google::protobuf::uint32 RtpsParticipantAttr::domain_id_gain() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.RtpsParticipantAttr.domain_id_gain)
  return domain_id_gain_;
}
inline void RtpsParticipantAttr::set_domain_id_gain(::google::protobuf::uint32 value) {
  set_has_domain_id_gain();
  domain_id_gain_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.RtpsParticipantAttr.domain_id_gain)
}

// optional uint32 port_base = 4 [default = 10000];
inline bool RtpsParticipantAttr::has_port_base() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RtpsParticipantAttr::set_has_port_base() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RtpsParticipantAttr::clear_has_port_base() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RtpsParticipantAttr::clear_port_base() {
  port_base_ = 10000u;
  clear_has_port_base();
}
inline ::google::protobuf::uint32 RtpsParticipantAttr::port_base() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.RtpsParticipantAttr.port_base)
  return port_base_;
}
inline void RtpsParticipantAttr::set_port_base(::google::protobuf::uint32 value) {
  set_has_port_base();
  port_base_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.RtpsParticipantAttr.port_base)
}

// -------------------------------------------------------------------

// CommunicationMode

// optional .apollo.cyber.proto.OptionalMode same_proc = 1 [default = INTRA];
inline bool CommunicationMode::has_same_proc() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CommunicationMode::set_has_same_proc() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CommunicationMode::clear_has_same_proc() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CommunicationMode::clear_same_proc() {
  same_proc_ = 1;
  clear_has_same_proc();
}
inline ::apollo::cyber::proto::OptionalMode CommunicationMode::same_proc() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.CommunicationMode.same_proc)
  return static_cast< ::apollo::cyber::proto::OptionalMode >(same_proc_);
}
inline void CommunicationMode::set_same_proc(::apollo::cyber::proto::OptionalMode value) {
  assert(::apollo::cyber::proto::OptionalMode_IsValid(value));
  set_has_same_proc();
  same_proc_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.CommunicationMode.same_proc)
}

// optional .apollo.cyber.proto.OptionalMode diff_proc = 2 [default = SHM];
inline bool CommunicationMode::has_diff_proc() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CommunicationMode::set_has_diff_proc() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CommunicationMode::clear_has_diff_proc() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CommunicationMode::clear_diff_proc() {
  diff_proc_ = 2;
  clear_has_diff_proc();
}
inline ::apollo::cyber::proto::OptionalMode CommunicationMode::diff_proc() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.CommunicationMode.diff_proc)
  return static_cast< ::apollo::cyber::proto::OptionalMode >(diff_proc_);
}
inline void CommunicationMode::set_diff_proc(::apollo::cyber::proto::OptionalMode value) {
  assert(::apollo::cyber::proto::OptionalMode_IsValid(value));
  set_has_diff_proc();
  diff_proc_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.CommunicationMode.diff_proc)
}

// optional .apollo.cyber.proto.OptionalMode diff_host = 3 [default = RTPS];
inline bool CommunicationMode::has_diff_host() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CommunicationMode::set_has_diff_host() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CommunicationMode::clear_has_diff_host() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CommunicationMode::clear_diff_host() {
  diff_host_ = 3;
  clear_has_diff_host();
}
inline ::apollo::cyber::proto::OptionalMode CommunicationMode::diff_host() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.CommunicationMode.diff_host)
  return static_cast< ::apollo::cyber::proto::OptionalMode >(diff_host_);
}
inline void CommunicationMode::set_diff_host(::apollo::cyber::proto::OptionalMode value) {
  assert(::apollo::cyber::proto::OptionalMode_IsValid(value));
  set_has_diff_host();
  diff_host_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.CommunicationMode.diff_host)
}

// -------------------------------------------------------------------

// ResourceLimit

// optional uint32 max_history_depth = 1 [default = 1000];
inline bool ResourceLimit::has_max_history_depth() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResourceLimit::set_has_max_history_depth() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResourceLimit::clear_has_max_history_depth() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResourceLimit::clear_max_history_depth() {
  max_history_depth_ = 1000u;
  clear_has_max_history_depth();
}
inline ::google::protobuf::uint32 ResourceLimit::max_history_depth() const {
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.ResourceLimit.max_history_depth)
  return max_history_depth_;
}
inline void ResourceLimit::set_max_history_depth(::google::protobuf::uint32 value) {
  set_has_max_history_depth();
  max_history_depth_ = value;
  // @@protoc_insertion_point(field_set:apollo.cyber.proto.ResourceLimit.max_history_depth)
}

// -------------------------------------------------------------------

// TransportConf

// optional .apollo.cyber.proto.ShmConf shm_conf = 1;
inline bool TransportConf::has_shm_conf() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TransportConf::set_has_shm_conf() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TransportConf::clear_has_shm_conf() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TransportConf::clear_shm_conf() {
  if (shm_conf_ != NULL) shm_conf_->Clear();
  clear_has_shm_conf();
}
inline const ::apollo::cyber::proto::ShmConf& TransportConf::_internal_shm_conf() const {
  return *shm_conf_;
}
inline const ::apollo::cyber::proto::ShmConf& TransportConf::shm_conf() const {
  const ::apollo::cyber::proto::ShmConf* p = shm_conf_;
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.TransportConf.shm_conf)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::cyber::proto::ShmConf*>(
      &::apollo::cyber::proto::_ShmConf_default_instance_);
}
inline ::apollo::cyber::proto::ShmConf* TransportConf::release_shm_conf() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.TransportConf.shm_conf)
  clear_has_shm_conf();
  ::apollo::cyber::proto::ShmConf* temp = shm_conf_;
  shm_conf_ = NULL;
  return temp;
}
inline ::apollo::cyber::proto::ShmConf* TransportConf::mutable_shm_conf() {
  set_has_shm_conf();
  if (shm_conf_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::cyber::proto::ShmConf>(GetArenaNoVirtual());
    shm_conf_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.TransportConf.shm_conf)
  return shm_conf_;
}
inline void TransportConf::set_allocated_shm_conf(::apollo::cyber::proto::ShmConf* shm_conf) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete shm_conf_;
  }
  if (shm_conf) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      shm_conf = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, shm_conf, submessage_arena);
    }
    set_has_shm_conf();
  } else {
    clear_has_shm_conf();
  }
  shm_conf_ = shm_conf;
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.TransportConf.shm_conf)
}

// optional .apollo.cyber.proto.RtpsParticipantAttr participant_attr = 2;
inline bool TransportConf::has_participant_attr() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TransportConf::set_has_participant_attr() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TransportConf::clear_has_participant_attr() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TransportConf::clear_participant_attr() {
  if (participant_attr_ != NULL) participant_attr_->Clear();
  clear_has_participant_attr();
}
inline const ::apollo::cyber::proto::RtpsParticipantAttr& TransportConf::_internal_participant_attr() const {
  return *participant_attr_;
}
inline const ::apollo::cyber::proto::RtpsParticipantAttr& TransportConf::participant_attr() const {
  const ::apollo::cyber::proto::RtpsParticipantAttr* p = participant_attr_;
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.TransportConf.participant_attr)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::cyber::proto::RtpsParticipantAttr*>(
      &::apollo::cyber::proto::_RtpsParticipantAttr_default_instance_);
}
inline ::apollo::cyber::proto::RtpsParticipantAttr* TransportConf::release_participant_attr() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.TransportConf.participant_attr)
  clear_has_participant_attr();
  ::apollo::cyber::proto::RtpsParticipantAttr* temp = participant_attr_;
  participant_attr_ = NULL;
  return temp;
}
inline ::apollo::cyber::proto::RtpsParticipantAttr* TransportConf::mutable_participant_attr() {
  set_has_participant_attr();
  if (participant_attr_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::cyber::proto::RtpsParticipantAttr>(GetArenaNoVirtual());
    participant_attr_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.TransportConf.participant_attr)
  return participant_attr_;
}
inline void TransportConf::set_allocated_participant_attr(::apollo::cyber::proto::RtpsParticipantAttr* participant_attr) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete participant_attr_;
  }
  if (participant_attr) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      participant_attr = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, participant_attr, submessage_arena);
    }
    set_has_participant_attr();
  } else {
    clear_has_participant_attr();
  }
  participant_attr_ = participant_attr;
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.TransportConf.participant_attr)
}

// optional .apollo.cyber.proto.CommunicationMode communication_mode = 3;
inline bool TransportConf::has_communication_mode() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TransportConf::set_has_communication_mode() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TransportConf::clear_has_communication_mode() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TransportConf::clear_communication_mode() {
  if (communication_mode_ != NULL) communication_mode_->Clear();
  clear_has_communication_mode();
}
inline const ::apollo::cyber::proto::CommunicationMode& TransportConf::_internal_communication_mode() const {
  return *communication_mode_;
}
inline const ::apollo::cyber::proto::CommunicationMode& TransportConf::communication_mode() const {
  const ::apollo::cyber::proto::CommunicationMode* p = communication_mode_;
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.TransportConf.communication_mode)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::cyber::proto::CommunicationMode*>(
      &::apollo::cyber::proto::_CommunicationMode_default_instance_);
}
inline ::apollo::cyber::proto::CommunicationMode* TransportConf::release_communication_mode() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.TransportConf.communication_mode)
  clear_has_communication_mode();
  ::apollo::cyber::proto::CommunicationMode* temp = communication_mode_;
  communication_mode_ = NULL;
  return temp;
}
inline ::apollo::cyber::proto::CommunicationMode* TransportConf::mutable_communication_mode() {
  set_has_communication_mode();
  if (communication_mode_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::cyber::proto::CommunicationMode>(GetArenaNoVirtual());
    communication_mode_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.TransportConf.communication_mode)
  return communication_mode_;
}
inline void TransportConf::set_allocated_communication_mode(::apollo::cyber::proto::CommunicationMode* communication_mode) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete communication_mode_;
  }
  if (communication_mode) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      communication_mode = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, communication_mode, submessage_arena);
    }
    set_has_communication_mode();
  } else {
    clear_has_communication_mode();
  }
  communication_mode_ = communication_mode;
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.TransportConf.communication_mode)
}

// optional .apollo.cyber.proto.ResourceLimit resource_limit = 4;
inline bool TransportConf::has_resource_limit() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TransportConf::set_has_resource_limit() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TransportConf::clear_has_resource_limit() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TransportConf::clear_resource_limit() {
  if (resource_limit_ != NULL) resource_limit_->Clear();
  clear_has_resource_limit();
}
inline const ::apollo::cyber::proto::ResourceLimit& TransportConf::_internal_resource_limit() const {
  return *resource_limit_;
}
inline const ::apollo::cyber::proto::ResourceLimit& TransportConf::resource_limit() const {
  const ::apollo::cyber::proto::ResourceLimit* p = resource_limit_;
  // @@protoc_insertion_point(field_get:apollo.cyber.proto.TransportConf.resource_limit)
  return p != NULL ? *p : *reinterpret_cast<const ::apollo::cyber::proto::ResourceLimit*>(
      &::apollo::cyber::proto::_ResourceLimit_default_instance_);
}
inline ::apollo::cyber::proto::ResourceLimit* TransportConf::release_resource_limit() {
  // @@protoc_insertion_point(field_release:apollo.cyber.proto.TransportConf.resource_limit)
  clear_has_resource_limit();
  ::apollo::cyber::proto::ResourceLimit* temp = resource_limit_;
  resource_limit_ = NULL;
  return temp;
}
inline ::apollo::cyber::proto::ResourceLimit* TransportConf::mutable_resource_limit() {
  set_has_resource_limit();
  if (resource_limit_ == NULL) {
    auto* p = CreateMaybeMessage<::apollo::cyber::proto::ResourceLimit>(GetArenaNoVirtual());
    resource_limit_ = p;
  }
  // @@protoc_insertion_point(field_mutable:apollo.cyber.proto.TransportConf.resource_limit)
  return resource_limit_;
}
inline void TransportConf::set_allocated_resource_limit(::apollo::cyber::proto::ResourceLimit* resource_limit) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete resource_limit_;
  }
  if (resource_limit) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      resource_limit = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, resource_limit, submessage_arena);
    }
    set_has_resource_limit();
  } else {
    clear_has_resource_limit();
  }
  resource_limit_ = resource_limit;
  // @@protoc_insertion_point(field_set_allocated:apollo.cyber.proto.TransportConf.resource_limit)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace cyber
}  // namespace apollo

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::apollo::cyber::proto::OptionalMode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::cyber::proto::OptionalMode>() {
  return ::apollo::cyber::proto::OptionalMode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_transport_5fconf_2eproto
