variables:
  GIT_SUBMODULE_STRATEGY: recursive

Build CMake Ubuntu 18.04:
  image: "ubuntu:18.04"
  before_script:
    - apt-get update  -qq
    - apt-get install -qq -y build-essential libpcre3-dev libssl-dev libexpat1-dev libpq-dev unixodbc-dev libmysqlclient-dev libsqlite3-dev sloccount cppcheck ninja-build
  script:
    - mkdir cmake_build
    - cd cmake_build
    - cmake ..
    - make
